### ISSUE TITLE
local variable ‘atlasimage‘ referenced before assignment

### ISSUE THREAD

**Issue by wby920920** [icon-lab/BolT#1]
When I run 'python prep.py --dataset abide1', the following error occurs.
How to solve it?
<img width="528" alt="ebf9de21b427ff08632113a122219f8" src="https://user-images.githubusercontent.com/32837843/208672802-973d801f-7c35-4067-88cf-e9107cc70f6e.png">

**Comment by tuttyfrutyee** [comment]
Hi @wby920920,

From the error message, it seems like the atlasImage variable is not constructed in the prep_atlas.py file. And in the file, the variable is constructed in the if statement, which depends on the atlas name you provided. Currently, only "schaefer7_400" atlas is supported in the code, but you can modify it to try out other atlases.

**Comment by wby920920** [comment]
Do I need to put the schaefer7_400 atlas into the folder myself?

**Comment by tuttyfrutyee** [comment]
Hi @wby920920,

No, you do not need to. When calling python prep.py, you have to specify the atlas name like this. 

`python prep.py --atlas schaefer7_400`

Mistakenly I have initialized the default value to schaefer7_400_2mm, which mismatches with the if statement I mentioned before. So all you need to do is specify the atlas as I wrote. If there are any further problems, please do not hesitate to ask. I am more than happy to help.

**Comment by wby920920** [comment]
Thank you very much!
